# Generated by Django 6.0.7 on 2026-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_country',
            field=models.CharField(blank=True, help_text='Code pays ISO (ex: FR, US)', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_referrer_domain',
            field=models.CharField(blank=True, help_text='Domaine du referrer HTTP (ex: facebook.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
