# Generated by Django 6.0.7 on 2026-07-15 20:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('error', 'error')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('total_images', models.IntegerField(default=0)),
                ('total_videos', models.IntegerField(default=0)),
                ('progress', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('output_dir', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
