# Generated by Django 6.0.7 on 2026-07-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationjob',
            name='mode',
            field=models.CharField(choices=[('optimize_image', 'optimize_image'), ('optimize_video', 'optimize_video'), ('sign', 'sign'), ('smooth', 'smooth')], default='optimize_image', max_length=20),
        ),
        migrations.AddField(
            model_name='optimizationjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='optimizationjob',
            index=models.Index(fields=['status'], name='optimizer_o_status_7f615c_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationjob',
            index=models.Index(fields=['mode'], name='optimizer_o_mode_952a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationjob',
            index=models.Index(fields=['created_at'], name='optimizer_o_created_f990ef_idx'),
        ),
    ]
